name: singbox-server
services:
  sing-box:
    image: ghcr.io/sagernet/sing-box:1.13.14
    container_name: sing-box
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - "./config:/etc/sing-box"
    command: run -c /etc/sing-box/config.json

  sub-server:
    image: nginx:alpine
    container_name: sub-server
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - "./config/subs:/usr/share/nginx/html/subs:ro"